---
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          # Yourself
          - 0.0.0.0:9090
  - job_name: sgx-testing
    static_configs:
      - targets:
          - sgx-testing.da-int.net:9464
        labels:
          namespace: sgx-testing
          pod: canton
          container: canton
  - job_name: canton-testing-2
    static_configs:
      - targets:
          - canton-testing-2.da-int.net:9464
        labels:
          namespace: canton-testing-2
          pod: canton
          container: canton
  - job_name: canton-testing-synchronizers
    static_configs:
      - targets:
          - canton-testing.da-int.net:9001
        labels:
          namespace: canton-testing-synchronizers
          pod: canton
          container: canton
  - job_name: canton-testing-synchronizers-sec
    static_configs:
      - targets:
          - canton-testing.da-int.net:9002
        labels:
          namespace: canton-testing-synchronizers-sec
          pod: canton
          container: canton
  - job_name: canton-testing-participants
    static_configs:
      - targets:
          - canton-testing.da-int.net:9003
        labels:
          namespace: canton-testing-participants
          pod: canton
          container: canton
  - job_name: canton-testing-participants-sec
    static_configs:
      - targets:
          - canton-testing.da-int.net:9004
        labels:
          namespace: canton-testing-participants-sec
          pod: canton
          container: canton
  - job_name: canton-testing-performance-runners
    static_configs:
      - targets:
          - canton-testing.da-int.net:9005
        labels:
          namespace: canton-testing-performance-runners
          pod: canton
          container: canton

  - job_name: grafana
    static_configs:
      - targets:
          # Docker compose service
          - grafana:3000
  - job_name: exporter
    static_configs:
      - targets:
          # Docker compose service
          - exporter:9100
  - job_name: postgres
    static_configs:
      - targets:
          # Docker compose service
          - postgres-exporter:9187
