description: >
  Commands that copies a local file to Azure Storage Account
parameters:
  job_name:
    type: string
    description: Optional name for description
    default: ''
  path:
    type: string
    description: A local file or path
  key:
    type: string
    description: Cache Key to store under
  CONTAINER:
    type: env_var_name
    default: CONTAINER_URL
steps:
  - run:
      name: << parameters.job_name >> - Saving using AzCopy
      environment:
        ORB_PATH: << parameters.path >>
        ORB_KEY: << parameters.key >>
        ORB_CONTAINER: <<parameters.CONTAINER>>
      command: <<include(scripts/save-to-azure.sh)>>
