triggers:
  - schedule:
      cron: "30 7 * * 1-5" # In the morning on Monday-Friday, 3 hours after the daml release cron start
      filters:
        branches:
          only:
            - main
jobs:
  - daml_upgrade_pr:
      context:
        - artifactory
        - canton-daml-update-pr
        - azure-self-cache
        - maven-mirror
        - da-images
